### ISSUE TITLE
Problem with Installation

### ISSUE THREAD

**Issue by Umeshagouda** [RandomWireTechnologies/ctrl-o-server#15]
I did't get how to install this can you help me out? or provide any installation method...
when we login its identify "auth" folder but i did't get that folder..

**Comment by pataelmo** [comment]
Sorry, I haven't created a proper installation instruction for this software.

First your question.  There is no auth folder because that's not how the framework works.  This site is based on [Code Igniter.](http://www.codeigniter.com/user_guide/overview/at_a_glance.html)

If you get the login screen up, you should just use the register button to create a new account fit yourself.  Once you've done that then login to the mysql database you setup and change the fields to make your user be an admin.  (I need to look at the structure again to detail this step).

**Comment by pataelmo** [comment]
This was an issue with mod_rewrite not being enabled.  Through debugging this I discovered another issue, for both installation documentation and for code design.  I will open a new issue for tracking that getting fixed.  For now this server is up and running.

**Comment by Umeshagouda** [comment]
Thank you patrick

Regatds,
Umesh

On Fri, Mar 27, 2015 at 8:08 PM, Patrick <notifications@github.com> wrote:

> This was an issue with mod_rewrite not being enabled. Through debugging
> this I discovered another issue, for both installation documentation and
> for code design. I will open a new issue for tracking that getting fixed.
> For now this server is up and running.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RandomWireTechnologies/ctrl-o-server/issues/15#issuecomment-86961311>
> .
>



-- 
Regards,
Umesh s patil
